#!/usr/bin/env bash
# Transfers a file from shool client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Store the command-line arguments in variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~

echo "File transfer complete."
