#!/usr/bin/env bash 
# Install and setup nginx server 

sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html

if [[ $(pgrep nginx) ]]; then
    sudo service nginx restart
else
   sudo service nginx start
fi
