#!/usr/bin/env bash

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install nginx -y
fi

# Configure Nginx to redirect /redirect_me to another page
sudo sed -i '29i\\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
