#!/usr/bin/env bash
# Configure server with Nginx redirection
# Update the Nginx configuration file to redirect /redirect_me to another page with a 301 Moved Permanently response
sudo sed -i '/^.*location \/redirect_me {/a \        return 301 https://www.example.com/;\n' /etc/nginx/sites-available/default
sudo service nginx reload
