#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

# Install Nginx
apt-get update
apt-get install -y nginx

# Create custom 404 error page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/custom_404.html

# Update Nginx configuration
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

# Restart Nginx service
service nginx restart
