#!/usr/bin/env bash
# install nginx on your web-01 server

# Install Nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart

# Reload Nginx service
sudo service nginx reload
