#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo sed -i '/error_page 404/a \\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^}/i \\\tlocation / {\n\t\terror_page 404 /404.html;\n\t}' /etc/nginx/sites-available/default

sudo service nginx reload
