#!/usr/bin/env bash
# Installs Nginx with the following:
# Contains a custom HTTP header (on web-01 and web-02) named X-Served-By.
# Listens on port 80.

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me 
https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/h404.html
sed -i '/listen 80 default_server/a 
error_page 404 /error-404.html;\n
location = /error-404.html {
\n\troot /var/www/html;\n\tinternal;\n
}' /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

service nginx restart
