#!/usr/bin/env bash
# Configure server with: HAproxy
# Install and configure HAproxy on your lb-01 server.

# Install HAproxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update -y
apt-get install -y haproxy=2.0.*

# Make sure HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=1/" /etc/default/haproxy

# Backup the original configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Update the HAproxy configuration file with the roundrobin algorithm and server information
cat << EOF > /etc/haproxy/haproxy.cfg
frontend http_front
  bind *:80
  mode http
  option forwardfor
  default_backend http_back

backend http_back
  balance roundrobin
  mode http
  server 116739-web-01 54.236.17.124:80 check
  server 116739-web-02 100.24.237.123:80 check
EOF

# Restart the HAproxy service
systemctl enable haproxy
systemctl restart haproxy.service
