#!/usr/bin/env bash

# Install HAproxy and configure it to load balance
# traffic between two web servers

# Update package list
apt-get update -y

# Install HAproxy
apt-get install -y haproxy

# Backup the default HAproxy config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAproxy to load balance between two web servers
cat << EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 116739-web-01 54.236.17.124:80 check
    server 116739-web-02 100.24.237.123:80 check
EOF

# Start the HAproxy service
service haproxy start
