#!/bin/bash
# Configures an Nginx server to listen on port 80.

# Check if Nginx is running
if ! systemctl is-active --quiet nginx.service; then
    systemctl start nginx.service
fi

# Check if Nginx is listening on port 80
if ! netstat -plntu | grep nginx | grep ':80'; then
    # Backup the original configuration file
    cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup

    # Replace the original configuration file with a new one
    echo "worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location / {
                root /var/www/html;
                index index.html;
            }
        }
    }" > /etc/nginx/nginx.conf

    # Restart Nginx
    systemctl restart nginx.service
fi
