#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Install nginx
apt-get update -y
apt-get install nginx -y

# Change default port to 80 and start nginx
sed -i "s/listen.*/listen 80;/g" /etc/nginx/sites-available/default
service nginx start
